import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth } from "@/auth";
import { SignIn } from "./ui/sign-in";
import { SignOut } from "./ui/sign-out";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Recipes App",
  description: "Generated by create next app",
};

export async function Header() {
  const session = await auth();

  if (session === null || session.user === undefined) {
    return <SignIn />
  }
 
  return (
    <div>
      <p>{session.user.name || "Unknown Name"}</p>
      <p>{session.user.email || "Unknown Email"}</p>
      <img src={session.user.image || undefined} alt="User Avatar" />
      <SignOut />
    </div>
  )
} 

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
